name: Continuous Integration

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: 24
          cache: gradle
      - name: Build
        run:
          chmod +x ./gradlew;
          ./gradlew --no-daemon build
